### Get All Students

GET http://localhost:8080/academics/api/student
Accept: application/json

### Create A New Student

POST http://localhost:8080/academics/api/student
Content-Type: application/json

{
"email": "johndoe@mail.com",
"name": "John Doe",
"username": "john",
"password": "jd",
"courseCode": 1
}

### Get All Courses

GET http://localhost:8080/academics/api/course
Accept: application/json

### Create A New Course

POST http://localhost:8080/academics/api/course
Content-Type: application/json

{
  "code": 3,
  "name": "SI"
}
